version: "3.9"

services:
  tomcat:
#    image: sc
    image: tomcat:9
    volumes:
      - ./target/sc.war:/usr/local/tomcat/webapps/ROOT.war
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
      - "./scripts/init.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: committee-root
      MYSQL_PASSWORD: committee-root
      MYSQL_DATABASE: selection-committee-db
    ports:
      - "3307:3306"
volumes:
  mysql-data:
    driver: local
